
language: c

sudo: false

os:
  - linux

compiler:
  - clang

notifications:
  email:
    recipients:
      - alex.shaw.as@gmail.com
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - cmake
      - cmake-data
      - gcc-4.9
      - g++-4.9
      - ninja-build

env:
  global:
    - CMAKE_ARGS="-DCMAKE_C_COMPILER=/usr/bin/clang-3.6 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-3.6"
  matrix:
    - CMAKE_BUILD_TYPE="Debug"
    - CMAKE_BUILD_TYPE="Release"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $CMAKE_ARGS -G Ninja ..

script:
  - cmake --build . --config $CMAKE_BUILD_TYPE --target all
